[package]
name = "token_burns_and_distributions"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.4.1"
solana-program = "1.7.0"

[dependencies.spl-token]
version = "3.1.1"
features = ["no-entrypoint"]

[features]
no-entrypoint = []