[package]
name = "competitions_and_leaderboards"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.14.0"
solana-program = "1.7.0"

[dev-dependencies]
anchor-client = "0.14.0"
solana-client = "1.7.0"
solana-sdk = "1.7.0"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "competitions_and_leaderboards"
path = "src/main.rs"