[package]
name = "basic-token-contract"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.14.0"
solana-program = "1.7.0"

[dev-dependencies]
anchor-client = "0.14.0"
solana-client = "1.7.0"
solana-sdk = "1.7.0"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = ["cpi"]